### ISSUE TITLE
Re - Write the Non ConformityReport in the new React UI

### ISSUE THREAD

**Issue by mozzy11** [I-TECH-UW/OpenELIS-Global-2#760] opened 2024-03-05 21:06 UTC
Link : https://oe3.openelis-global.org/api/OpenELIS-Global/Report?type=patient&report=haitiNonConformityByDate

**Comment by manzil-infinity180** [comment] 2024-03-06 12:48
@mozzy11 i want to work on it please assign to me

**Comment by KutsJoe** [comment] 2024-03-11 12:24
Hello @manzil-infinity180 , are you still working on this? If not please @mozzy11 , assign this to me. Thanks.

**Comment by manzil-infinity180** [comment] 2024-03-11 12:25
> Hello @manzil-infinity180 , are you still working on this? If not please @mozzy11 , assign this to me. Thanks.

I am working in it will raise a pr soon

**Comment by Agaba-derrick** [comment] 2024-03-12 13:54
hey i have a WIP pr for this, do you mind reviewing ?

**Comment by mozzy11** [comment] 2024-03-20 17:30
https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/792

**Comment by Agaba-derrick** [comment] 2024-03-20 18:13
hey @konavivekramakrishna I hadn't noticed since the issue is not mentioned in your PR so I will close this

**Comment by mozzy11** [comment] 2024-03-22 07:14
Thanks @konavivekramakrishna

**Closed** 2024-03-22 07:14 UTC
